services:
  hit-switchbot-webui:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: hit-switchbot-webui
    ports:
      - "8092:8092"
    volumes:
      - ./app.env:/secrets/app.env:ro
    restart: unless-stopped
